public class Constants {

	internal struct Default {

		internal static let AppID: String = "tp7754"
		internal static let AuthType: String = "TID"
		internal static let LocaleIdentifier: String = "en_US_POSIX"
		internal static let PassCode: String = "tp_api"
		internal static let TimeoutInterval: Double = 60.0
	}

	public class ServerURL {

		internal static let Production: String = "https://www.gotapnow.com/api/v1.2.1/app/"
		internal static let Test: String = "http://tapapi.gotapnow.com/api/V1.2.1/app/"

		public static func getProductionURL() -> String {

			return Production
		}

		public static func getTestURL() -> String {

			return Test
		}
	}

	public class DateFormat {

		internal static let Format1: String = "yyyy-MM-dd'T'HH:mm:ss.SSSSSSzzz"
		internal static let Format2: String = "yyyy-MM-dd'T'HH:mm:ss"
		internal static let Format3: String = "ddMMyyyyHHmmssSSS"
		internal static let Format4: String = "EEE',' dd MMM yyyy HH':'mm':'ss 'GMT'"

		public static func getFormat1() -> String {

			return Format1
		}

		public static func getFormat2() -> String {

			return Format2
		}

		public static func getFormat3() -> String {

			return Format3
		}

		public static func getFormat4() -> String {

			return Format4
		}
	}

	internal struct Error {

        internal struct UserInfoKey {
            
            internal static let RequestHeaders: String = "RequestHeaders"
            internal static let RequestParameters: String = "RequestParameters"
            internal static let ResponseHeaders: String = "ResponseHeaders"
            internal static let ResponseParameters: String = "ResponseParameters"
            internal static let URL: String = "URL"
        }
        
		internal static let domain = "company.tap.goTap.goTapAPI"

		internal struct Code {

			internal static let DataSourceNotSet: Int64 = 10001
			internal static let DelegateNotSet: Int64 = 10002
			internal static let RequestOperationsManagerNotSet: Int64 = 10003
			internal static let RequestURLIncorrect: Int64 = 10004
			internal static let FailedToCreateRequest: Int64 = 10005
		}

		internal struct Title {

			internal static let Default: String = "API Client error"
		}

		internal struct Message {

			internal static let DataSourceNotSet: String = "API Client requires data source to work."
			internal static let DelegateNotSet: String = "API Client requires delegate to work."
			internal static let RequestOperationsManagerNotSet: String = "API Client requires request operations manager to work."
			internal static let RequestURLIncorrect: String = "Request URL is incorrect."
			internal static let FailedToCreateRequest: String = "Failed to create HTTP request."
		}
	}

	internal class Key {

        internal static let hd720: String = "hd720"
        internal static let thumbnail_url: String = "thumbnail_url"
        internal static let Last_Modified: String = "Last-Modified"
        internal static let length_seconds: String = "length_seconds"
        internal static let medium: String = "medium"
        internal static let moreInfo: String = "moreInfo"
        internal static let small: String = "small"
        internal static let string: String = "string"
        internal static let title: String = "title"
		internal static let Action: String = "Action"
		internal static let ActionType: String = "ActionType"
		internal static let ActiveSectors: String = "ActiveSectors"
		internal static let AddedType: String = "AddedType"
		internal static let AdditionalInfo: String = "AdditionalInfo"
		internal static let AddListScreen: String = "AddListScreen"
		internal static let AddListScreenID: String = "AddListScreenID"
		internal static let Address: String = "Address"
		internal static let Addresses: String = "Addresses"
		internal static let AddressHdrDtls: String = "AddressHdrDtls"
		internal static let AddressHdrs: String = "AddressHdrs"
		internal static let Address1: String = "Address1"
		internal static let Address2: String = "Address2"
		internal static let Amount: String = "Amount"
		internal static let AmountDetails: String = "AmountDetails"
		internal static let AMT: String = "AMT"
		internal static let Apartment: String = "Apartment"
		internal static let AppData: String = "AppData"
		internal static let APPID: String = "APPID"
		internal static let AppID: String = "AppID"
		internal static let AppInsCount: String = "AppInsCount"
		internal static let APPLicenseCD: String = "APPLicenseCD"
		internal static let APP_Mode: String = "APP-Mode"
		internal static let APP_Version: String = "APP-Version"
		internal static let Area: String = "Area"
		internal static let As: String = "As"
		internal static let AuthType: String = "AuthType"
		internal static let Avenue: String = "Avenue"
		internal static let background: String = "background"
		internal static let Badge: String = "Badge"
		internal static let BankID: String = "BankID"
		internal static let BankName: String = "BankName"
		internal static let BillingAddrFormat: String = "BillingAddrFormat"
		internal static let BIN: String = "BIN"
		internal static let BINLookup: String = "BINLookup"
		internal static let BINNumber: String = "BINNumber"
		internal static let Birthday: String = "Birthday"
		internal static let BizAcN: String = "BizAcN"
		internal static let BizFields: String = "BizFields"
		internal static let BizID: String = "BizID"
		internal static let Block: String = "Block"
		internal static let border: String = "border"
		internal static let Building: String = "Building"
		internal static let BuiThemeUrl: String = "BuiThemeUrl"
		internal static let Businesses: String = "Businesses"
		internal static let BusinessID: String = "BusinessID"
		internal static let Camera: String = "Camera"
		internal static let CanDelete: String = "CanDelete"
		internal static let CanPay: String = "CanPay"
		internal static let CardBrand: String = "CardBrand"
		internal static let CardCategory: String = "CardCategory"
		internal static let CardID: String = "CardID"
		internal static let CardImg: String = "CardImg"
		internal static let CardInfo: String = "CardInfo"
		internal static let CardNmbr: String = "CardNmbr"
		internal static let CardType: String = "CardType"
		internal static let CardTypeID: String = "CardTypeID"
		internal static let CarrierCode: String = "CarrierCode"
		internal static let CCD: String = "CCD"
		internal static let CID: String = "CID"
		internal static let City: String = "City"
		internal static let CnfrmCode: String = "CnfrmCode"
		internal static let CNO: String = "CNO"
		internal static let Cntry: String = "Cntry"
		internal static let CntryID: String = "CntryID"
		internal static let CntryName: String = "CntryName"
		internal static let Code: String = "Code"
		internal static let Contacts: String = "Contacts"
		internal static let Count: String = "Count"
		internal static let Country: String = "Country"
		internal static let CountryCode: String = "CountryCode"
		internal static let CountryImgUrl: String = "CountryImgUrl"
		internal static let CountryName: String = "CountryName"
		internal static let CreationDate: String = "CreationDate"
		internal static let CTP: String = "CTP"
		internal static let CurrencyCD: String = "CurrencyCD"
		internal static let CurrencyCode: String = "CurrencyCode"
		internal static let CurrencySymbol: String = "CurrencySymbol"
		internal static let CVV: String = "CVV"
		internal static let Data: String = "Data"
		internal static let Date: String = "Date"
		internal static let DefaultID: String = "DefaultID"
		internal static let Department: String = "Department"
		internal static let Description: String = "Description"
		internal static let DeviceID: String = "DeviceID"
		internal static let DeviceModel: String = "DeviceModel"
		internal static let DeviceName: String = "DeviceName"
		internal static let DeviceToken: String = "DeviceToken"
		internal static let dial_number: String = "dial_number"
		internal static let DiscAmount: String = "DiscAmount"
		internal static let DiscPer: String = "DiscPer"
		internal static let Display: String = "Display"
		internal static let DispOrder: String = "DispOrder"
		internal static let DtlDesc: String = "DtlDesc"
		internal static let DtlDispValue: String = "DtlDispValue"
		internal static let DtlID: String = "DtlID"
		internal static let DtlTitle: String = "DtlTitle"
		internal static let DueDate: String = "DueDate"
		internal static let EditCard: String = "EditCard"
		internal static let EditCurr: String = "EditCurr"
		internal static let EmailAddresses: String = "EmailAddresses"
		internal static let EnableAlert: String = "EnableAlert"
		internal static let Enabled: String = "Enabled"
		internal static let EXP: String = "EXP"
		internal static let ExpiryDate: String = "ExpiryDate"
		internal static let ExtraCharge: String = "ExtraCharge"
		internal static let FieldName: String = "FieldName"
		internal static let FieldType: String = "FieldType"
		internal static let FieldVal: String = "FieldVal"
		internal static let FirstName: String = "FirstName"
		internal static let FlagURL: String = "FlagURL"
		internal static let FldDataTyp: String = "FldDataTyp"
		internal static let FldID: String = "FldID"
		internal static let FldName: String = "FldName"
		internal static let Floor: String = "Floor"
		internal static let GateWayID: String = "GateWayID"
		internal static let get_balance: String = "get_balance"
		internal static let GID: String = "GID"
		internal static let Governarate: String = "Governarate"
		internal static let GreetingURL: String = "GreetingURL"
		internal static let GroupID: String = "GroupID"
		internal static let GroupItemOrderBy: String = "GroupItemOrderBy"
		internal static let GroupName: String = "GroupName"
		internal static let Groups: String = "Groups"
		internal static let gsm_number: String = "gsm_number"
		internal static let HasCustomAmount: String = "HasCustomAmount"
		internal static let HdrDtlID: String = "HdrDtlID"
		internal static let HdrID: String = "HdrID"
		internal static let HeaderAttributes: String = "HeaderAttributes"
		internal static let HighlightedColor: String = "HighlightedColor"
		internal static let HomeItemDtls: String = "HomeItemDtls"
		internal static let HomeItems: String = "HomeItems"
		internal static let hsCode: String = "hsCode"
		internal static let HsCode: String = "HsCode"
		internal static let Icon: String = "Icon"
		internal static let icon: String = "icon"
		internal static let ID: String = "ID"
		internal static let IDNmbr: String = "IDNmbr"
		internal static let IDPattern: String = "IDPattern"
		internal static let IDS: String = "IDS"
		internal static let IDType: String = "IDType"
		internal static let IItemHdrDtls: String = "IItemHdrDtls"
		internal static let ImageData: String = "ImageData"
		internal static let Images: String = "Images"
		internal static let ImageURL: String = "ImageURL"
		internal static let ImageUrls: String = "ImageUrls"
		internal static let InputData: String = "InputData"
		internal static let InputFields: String = "InputFields"
		internal static let InstantMessages: String = "InstantMessages"
		internal static let is_primary_number: String = "is_primary_number"
		internal static let IsAuthReq: String = "IsAuthReq"
		internal static let IsCollectionAvl: String = "IsCollectionAvl"
		internal static let IsDefault: String = "IsDefault"
		internal static let ISDNMbr: String = "ISDNMbr"
		internal static let ISDNmbr: String = "ISDNmbr"
		internal static let IsDtldItem: String = "IsDtldItem"
		internal static let ISOCode: String = "ISOCode"
		internal static let ISP: String = "ISP"
		internal static let IsSrlAvailable: String = "IsSrlAvailable"
		internal static let IsSrlLoaded: String = "IsSrlLoaded"
		internal static let IsTipAvail: String = "IsTipAvail"
		internal static let Item: String = "Item"
		internal static let ItemHdrs: String = "ItemHdrs"
		internal static let ItemID: String = "ItemID"
		internal static let ItemOrderBy: String = "ItemOrderBy"
		internal static let ItemRowType: String = "ItemRowType"
		internal static let Items: String = "Items"
		internal static let ItemType: String = "ItemType"
		internal static let JobTitle: String = "JobTitle"
		internal static let LangCode: String = "LangCode"
		internal static let LanguageFont: String = "LanguageFont"
		internal static let LastName: String = "LastName"
		internal static let LastUpdatedOn: String = "LastUpdatedOn"
		internal static let Lat: String = "Lat"
		internal static let Latitude: String = "Latitude"
		internal static let LayerImgUpdates: String = "LayerImgUpdates"
		internal static let LayerIndex: String = "LayerIndex"
		internal static let LinkedAccDesc: String = "LinkedAccDesc"
		internal static let LinkedItems: String = "LinkedItems"
		internal static let LinkID: String = "LinkID"
		internal static let localeIdentifier: String = "localeIdentifier"
		internal static let localeName: String = "localeName"
		internal static let LocalizationData: String = "LocalizationData"
		internal static let LocalizedModel: String = "LocalizedModel"
		internal static let Location: String = "Location"
		internal static let LogoID: String = "LogoID"
		internal static let Logos: String = "Logos"
		internal static let LogoURL: String = "LogoURL"
		internal static let Lon: String = "Lon"
		internal static let Longitude: String = "Longitude"
		internal static let LstID: String = "LstID"
		internal static let LstName: String = "LstName"
		internal static let LstOption: String = "LstOption"
		internal static let MaxAmount: String = "MaxAmount"
		internal static let MaxLngth: String = "MaxLngth"
		internal static let Medium: String = "Medium"
		internal static let Message: String = "Message"
		internal static let MiddleName: String = "MiddleName"
		internal static let MinAmount: String = "MinAmount"
		internal static let MobileVerify: String = "MobileVerify"
		internal static let ModificationDate: String = "ModificationDate"
		internal static let Msg: String = "Msg"
		internal static let MsgDetails: String = "MsgDetails"
		internal static let MyList: String = "MyList"
		internal static let Name: String = "Name"
		internal static let NameonCard: String = "NameonCard"
		internal static let NewSectors: String = "NewSectors"
		internal static let NextID: String = "NextID"
		internal static let NextUpdateDate: String = "NextUpdateDate"
		internal static let NMC: String = "NMC"
		internal static let NormalColor: String = "NormalColor"
		internal static let NormalImg: String = "NormalImg"
		internal static let Notifications: String = "Notifications"
		internal static let Number: String = "Number"
		internal static let NumberPattern: String = "NumberPattern"
		internal static let Offset: String = "Offset"
		internal static let Option: String = "Option"
		internal static let OrderBy: String = "OrderBy"
		internal static let Orders: String = "Orders"
		internal static let Org: String = "Org"
		internal static let OrganizationName: String = "OrganizationName"
		internal static let ParamList: String = "ParamList"
		internal static let ParamName: String = "ParamName"
		internal static let Params: String = "Params"
		internal static let ParamValue: String = "ParamValue"
		internal static let PassCode: String = "PassCode"
		internal static let Password: String = "Password"
		internal static let PayAndCollect: String = "PayAndCollect"
		internal static let PayCurrCode: String = "PayCurrCode"
		internal static let PayCurrencyCD: String = "PayCurrencyCD"
		internal static let PayCurrencySymbol: String = "PayCurrencySymbol"
		internal static let PayDesc: String = "PayDesc"
		internal static let PayDetails: String = "PayDetails"
		internal static let PayExtraCharge: String = "PayExtraCharge"
		internal static let PayLater: String = "PayLater"
		internal static let PaymentCards: String = "PaymentCards"
		internal static let PayNow: String = "PayNow"
		internal static let PayProcessID: String = "PayProcessID"
		internal static let PayRefNumber: String = "PayRefNumber"
		internal static let PayTxnAmount: String = "PayTxnAmount"
		internal static let PhNumber: String = "PhNumber"
		internal static let PhoneNmbr: String = "PhoneNmbr"
		internal static let PhoneNumber: String = "PhoneNumber"
		internal static let Phones: String = "Phones"
		internal static let Photos: String = "Photos"
		internal static let POBox: String = "POBox"
		internal static let PostalCode: String = "PostalCode"
		internal static let PrdCurrCode: String = "PrdCurrCode"
		internal static let PrdDesc: String = "PrdDesc"
		internal static let PrdID: String = "PrdID"
		internal static let PrdImage: String = "PrdImage"
		internal static let PrdName: String = "PrdName"
		internal static let Prefix: String = "Prefix"
		internal static let Products: String = "Products"
		internal static let Purpose: String = "Purpose"
		internal static let Quantity: String = "Quantity"
		internal static let Query: String = "Query"
		internal static let ReceiptDetails: String = "ReceiptDetails"
		internal static let RecordID: String = "RecordID"
		internal static let RedeemUrl: String = "RedeemUrl"
		internal static let RefNmbr: String = "RefNmbr"
		internal static let RefValue: String = "RefValue"
		internal static let Region: String = "Region"
		internal static let RegionName: String = "RegionName"
		internal static let RelatedNames: String = "RelatedNames"
		internal static let Remarks: String = "Remarks"
		internal static let ReqType: String = "ReqType"
		internal static let RequestGender: String = "RequestGender"
		internal static let ReqFor: String = "ReqFor"
		internal static let Response: String = "Response"
		internal static let ResponseCode: String = "ResponseCode"
		internal static let ResponseID: String = "ResponseID"
		internal static let ResponseMsg: String = "ResponseMsg"
		internal static let RowID: String = "RowID"
		internal static let schedule_day: String = "schedule_day"
		internal static let schedule_setting: String = "schedule_setting"
		internal static let Screen: String = "Screen"
		internal static let ScreenID: String = "ScreenID"
		internal static let SctrImage: String = "SctrImage"
		internal static let SelectedColor: String = "SelectedColor"
		internal static let SelectOption: String = "SelectOption"
		internal static let SerialNumber: String = "SerialNumber"
		internal static let sessID: String = "sessID"
		internal static let SessionID: String = "SessionID"
		internal static let ShareAction: String = "ShareAction"
		internal static let shareFileURL: String = "shareFileURL"
		internal static let ShortUrl: String = "ShortUrl"
		internal static let Shorturls: String = "Shorturls"
		internal static let ShowCard: String = "ShowCard"
		internal static let ShowCode: String = "ShowCode"
		internal static let ShowScreen: String = "ShowScreen"
		internal static let ShowTutorials: String = "ShowTutorials"
		internal static let SIMCardCode: String = "SIMCardCode"
		internal static let SmallImg: String = "SmallImg"
		internal static let SMS: String = "SMS"
		internal static let sms_content: String = "sms_content"
		internal static let sms_to_sender: String = "sms_to_sender"
		internal static let SocialProfiles: String = "SocialProfiles"
		internal static let State: String = "State"
		internal static let StateAndZip: String = "StateAndZip"
		internal static let Status: String = "Status"
		internal static let Street: String = "Street"
		internal static let Style: String = "Style"
		internal static let Suffix: String = "Suffix"
		internal static let SystemName: String = "SystemName"
		internal static let SystemVersion: String = "SystemVersion"
		internal static let text: String = "text"
		internal static let threeLetters: String = "threeLetters"
		internal static let TimeZone: String = "TimeZone"
		internal static let TipAmount: String = "TipAmount"
		internal static let TipAvail: String = "TipAvail"
		internal static let TotalAmount: String = "TotalAmount"
		internal static let translationFileURL: String = "translationFileURL"
		internal static let twoLetters: String = "twoLetters"
		internal static let TxnAmount: String = "TxnAmount"
		internal static let TxnCard: String = "TxnCard"
		internal static let TXNCharges: String = "TXNCharges"
		internal static let TxnID: String = "TxnID"
		internal static let TxnURL: String = "TxnURL"
		internal static let Type_: String = "Type"
		internal static let Url: String = "Url"
		internal static let URLs: String = "URLs"
		internal static let UpdatedDate: String = "UpdatedDate"
		internal static let UserData: String = "UserData"
		internal static let UserInterfaceIdiom: String = "UserInterfaceIdiom"
		internal static let UsrMessage: String = "UsrMessage"
		internal static let ussd_code: String = "ussd_code"
		internal static let Value: String = "Value"
		internal static let VisibleInMyList: String = "VisibleInMyList"
		internal static let VisibleInRegistration: String = "VisibleInRegistration"
		internal static let VndID: String = "VndID"
		internal static let VndImage: String = "VndImage"
		internal static let VndName: String = "VndName"
		internal static let Zip: String = "Zip"
		internal static let ZipCode: String = "ZipCode"

		internal struct CountriesPlist {

			internal static let ISDNumber = "ISD Number"
			internal static let PhoneNumberPattern = "Phone Number Length"
			internal static let LanguageCode = "Language Code"
			internal static let FlagImageName = "Flag Image Name"
		}

		internal struct CountriesJSON {

			internal static let Can_Add_Civil_Id = "Can_Add_Civil_Id"
			internal static let Can_Add_Mobile = "Can_Add_Mobile"
			internal static let Can_Register = "Can_Register"
			internal static let Civil_Id_Validation = "Civil_Id_Validation"
			internal static let ISD_Number = "ISD_Number"
			internal static let Name = "Name"
			internal static let Numeric_ISO_Code = "Numeric_ISO_Code"
			internal static let Phone_Number_Validation = "Phone_Number_Validation"
			internal static let Three_Letter_ISO_Code = "Three_Letter_ISO_Code"
			internal static let Two_Letter_ISO_Code = "Two_Letter_ISO_Code"
		}

		internal struct ErrorUserInfo {

			internal static let Date: String = "Date"
			internal static let LocalizedDescription: String = "localized_description"
			internal static let LocalizedFailureReason: String = "localized_failure_reason"
			internal static let RequestHeaders: String = "RequestHeaders"
			internal static let RequestParameters: String = "RequestParameters"
			internal static let ResponseHeaders: String = "ResponseHeaders"
			internal static let ResponseParameters: String = "ResponseParameters"
			internal static let Title: String = "Title"
			internal static let URL: String = "URL"
		}

		internal struct ISOCodePlist {

			internal static let TwoLetters: String = "Two Letter ISO Code"
			internal static let ThreeLetters: String = "Three Letter ISO Code"
		}

		internal struct Localization {

			internal struct CardBrand {

				internal static let AiywaLoyalty: String = "AiywaLoyalty"
				internal static let AmericanExpress: String = "AmericanExpress"
				internal static let BENEFIT: String = "BENEFIT"
				internal static let CardGuard: String = "CardGuard"
				internal static let CBK: String = "CBK"
				internal static let Dankort: String = "Dankort"
				internal static let DinersClub: String = "DinersClub"
				internal static let Discover: String = "Discover"
				internal static let FAWRY: String = "FAWRY"
				internal static let InstaPayment: String = "InstaPayment"
				internal static let InterPayment: String = "InterPayment"
				internal static let JCB: String = "JCB"
				internal static let KNET: String = "KNET"
				internal static let MADA: String = "MADA"
				internal static let Maestro: String = "Maestro"
				internal static let MasterCard: String = "MasterCard"
				internal static let NAPS: String = "NAPS"
				internal static let NSPKMIR: String = "NSPKMIR"
				internal static let SADAD: String = "SADAD"
				internal static let Tap: String = "Tap"
				internal static let UATP: String = "UATP"
				internal static let UnionPay: String = "UnionPay"
				internal static let Verve: String = "Verve"
				internal static let Visa: String = "Visa"
				internal static let Viva: String = "Viva"
				internal static let Wataniya: String = "Wataniya"
				internal static let Zain: String = "Zain"
			}

			internal struct ItemType {

				internal static let Bill: String = "item_type_bill"
				internal static let Donation: String = "item_type_donation"
				internal static let Invoice: String = "item_type_invoice"
				internal static let Membership: String = "item_type_membership"
				internal static let Prepaid_card: String = "item_type_prepaid_card"
				internal static let Product: String = "item_type_product"
				internal static let Rent: String = "item_type_rent"
				internal static let Subscription: String = "item_type_subscription"
				internal static let Ticket: String = "item_type_ticket"
				internal static let Topup: String = "item_type_topup"
			}
		}

		internal struct UserSettings {

			internal static let AppID: String = "company.tap.goTap.AppID"
			internal static let AppLicenseCode: String = "company.tap.goTap.AppLicenseCode"
			internal static let DeviceID: String = "company.tap.goTap.DeviceID"
			internal static let PhoneNumber: String = "company.tap.goTap.PhoneNumber"
			internal static let PhoneNumberCountryCode: String = "company.tap.goTap.PhoneNumberCountryCode"
			internal static let SessionID: String = "company.tap.goTap.SessionID"
		}
	}

	internal struct Value {

		internal static let A: String = "A"
		internal static let ACCOUNTS: String = "ACCOUNTS"
		internal static let ACTIVE: String = "ACTIVE"
		internal static let Aiywa_Loyalty: String = "Aiywa Loyalty"
		internal static let ALL: String = "ALL"
		internal static let AMEX: String = "AMEX"
		internal static let BENEFIT: String = "BENEFIT"
		internal static let BILL: String = "BILL"
		internal static let CALL: String = "CALL"
		internal static let CARDGUARD: String = "CARDGUARD"
		internal static let CBK: String = "CBK"
		internal static let COUNTRY_CODE: String = "COUNTRY CODE"
		internal static let CREDIT: String = "CREDIT"
		internal static let D: String = "D"
		internal static let DANKORT: String = "DANKORT"
		internal static let DEBIT: String = "DEBIT"
		internal static let DELETE: String = "DELETE"
		internal static let DEV: String = "DEV"
		internal static let DINERS: String = "DINERS"
		internal static let DISCOVER: String = "DISCOVER"
		internal static let DOB: String = "DOB"
		internal static let DOC_NO: String = "DOC_NO"
		internal static let DOC_TYPE: String = "DOC_TYPE"
		internal static let DONATION: String = "DONATION"
		internal static let DP: String = "DP"
		internal static let EXP_DT: String = "EXP_DT"
		internal static let Facebook: String = "Facebook"
		internal static let FacebookMessenger: String = "FacebookMessenger"
		internal static let FAILED: String = "FAILED"
		internal static let FAWRY: String = "FAWRY"
		internal static let FEMALE: String = "FEMALE"
		internal static let FNAME: String = "FNAME"
		internal static let FRI: String = "FRI"
		internal static let GENDER: String = "GENDER"
		internal static let GET: String = "GET"
		internal static let GIVEN_NAMES: String = "GIVEN_NAMES"
		internal static let GooglePlus: String = "GooglePlus"
		internal static let HEAD: String = "HEAD"
		internal static let HOME: String = "HOME"
		internal static let ID: String = "ID"
		internal static let ID_NO: String = "ID_NO"
		internal static let Instagram: String = "Instagram"
		internal static let INSTAPAY: String = "INSTAPAY"
		internal static let INTERACTIVE: String = "INTERACTIVE"
		internal static let INTERPAY: String = "INTERPAY"
		internal static let INTRO: String = "INTRO"
		internal static let INVOICE: String = "INVOICE"
		internal static let ISSUE_CNTRY_CD: String = "ISSUE_CNTRY_CD"
		internal static let ITM_VIW: String = "ITM_VIW"
		internal static let JCB: String = "JCB"
		internal static let KNET: String = "KNET"
		internal static let L: String = "L"
		internal static let Linkedin: String = "Linkedin"
		internal static let LNAME: String = "LNAME"
		internal static let M: String = "M"
		internal static let MADA: String = "MADA"
		internal static let MAESTRO: String = "MAESTRO"
		internal static let Mail: String = "Mail"
		internal static let MALE: String = "MALE"
		internal static let MANUAL: String = "MANUAL"
		internal static let MASTERCARD: String = "MASTERCARD"
		internal static let MEMBERSHIP: String = "MEMBERSHIP"
		internal static let MENU: String = "MENU"
		internal static let MOBILE: String = "MOBILE"
		internal static let MON: String = "MON"
		internal static let MSG: String = "MSG"
		internal static let NAME: String = "NAME"
		internal static let NAPS: String = "NAPS"
		internal static let NATIONAL_CNTRY_CD: String = "NATIONAL_CNTRY_CD"
		internal static let NEW: String = "NEW"
		internal static let NONE: String = "NONE"
		internal static let NSPK: String = "NSPK"
		internal static let OPERATOR: String = "OPERATOR"
		internal static let ORD_DTL: String = "ORD_DTL"
		internal static let PAID: String = "PAID"
		internal static let PAY: String = "PAY"
		internal static let Phone: String = "Phone"
		internal static let POST: String = "POST"
		internal static let PRD: String = "PRD"
		internal static let PREPAIDCARD: String = "PREPAIDCARD"
		internal static let PRODUCT: String = "PRODUCT"
		internal static let R: String = "R"
		internal static let REFRESH: String = "REFRESH"
		internal static let REGID: String = "REGID"
		internal static let RENT: String = "RENT"
		internal static let S: String = "S"
		internal static let SADAD: String = "SADAD"
		internal static let SAT: String = "SAT"
		internal static let SCAN_ID: String = "SCAN_ID"
		internal static let schedule_amount: String = "schedule_amount"
		internal static let schedule_type: String = "schedule_type"
		internal static let schedule_value: String = "schedule_value"
		internal static let SCREEN: String = "SCREEN"
		internal static let SEX: String = "SEX"
		internal static let Share: String = "Share"
		internal static let SMS: String = "SMS"
		internal static let STATIC: String = "STATIC"
		internal static let STTS: String = "STTS"
		internal static let SUBS: String = "SUBS"
		internal static let SUN: String = "SUN"
		internal static let SURNAME: String = "SURNAME"
		internal static let T: String = "T"
		internal static let Tablet: String = "Tablet"
		internal static let TAP: String = "TAP"
		internal static let TELECOM: String = "TELECOM"
		internal static let TICKET: String = "TICKET"
		internal static let THU: String = "THU"
		internal static let TOPUP: String = "TOPUP"
		internal static let TUE: String = "TUE"
		internal static let Twitter: String = "Twitter"
		internal static let TXN: String = "TXN"
		internal static let U: String = "U"
		internal static let UATP: String = "UATP"
		internal static let UNIONPAY: String = "UNIONPAY"
		internal static let Unspecified: String = "Unspecified"
		internal static let UPDATE: String = "UPDATE"
		internal static let URL: String = "URL"
		internal static let V: String = "V"
		internal static let VAL: String = "VAL"
		internal static let VERVE: String = "VERVE"
		internal static let Video: String = "Video"
		internal static let VIEW: String = "VIEW"
		internal static let VISA: String = "VISA"
		internal static let Viva_PAY: String = "Viva PAY"
		internal static let W: String = "W"
		internal static let Wataniya_PAY: String = "Wataniya PAY"
		internal static let WED: String = "WED"
		internal static let Whatsapp: String = "Whatsapp"
		internal static let Y: String = "Y"
		internal static let Zain_PAY: String = "Zain PAY"
	}

	internal struct RequestPath {

		internal static let ConfirmOperator: String = "Home/ConfirmOperator"
		internal static let Contacts: String = "Account/Contacts"
		internal static let DeleteList: String = "Home/DeleteList"
		internal static let GetInvoiceDetails: String = "Home/GetInvoiceDetail"
		internal static let GetList: String = "Home/GetList"
		internal static let GetListDetails: String = "Home/GetListDetail"
		internal static let GetPushInvoiceDetails: String = "Home/GetPushInvoiceDetail"
		internal static let GetPushItemDetails: String = "Home/GetPushItemDetails"
		internal static let GetPushItems: String = "Home/GetPushItems"
		internal static let GetShortURLs: String = "Account/GetShortURL"
		internal static let GetTransactionDetails: String = "Payment/GetTxnDetails"
		internal static let GetUpdates: String = "Application/GetUpdates"
		internal static let GetVideo: String = "Home/TapPay/GetVideo"
		internal static let ItemViewedUpdate: String = "Home/ItemViewedUpdate"
		internal static let LinkAccounts: String = "Home/LinkAccounts"
		internal static let LinkEmail: String = "Payment/LinkEmail"
		internal static let PayItems: String = "Home/PayItems"
		internal static let PayTransaction: String = "Payment/PayTransaction"
		internal static let QuickAddList: String = "Home/QuickAddList"
		internal static let RateApp: String = "Payment/RateApp"
		internal static let Register: String = "Application/Register"
		internal static let RegistrationComplaint: String = "Complaint/Register"
		internal static let RequestApplication: String = "Application/Request"
		internal static let RequestSectors: String = "Application/RequestSector"
		internal static let ResendCode: String = "Application/ResendCode"
		internal static let SaveUserInfo: String = "Account/SaveUserInfo"
		internal static let ScheduleItem: String = "Home/ScheduleItem"
		internal static let ScheduleItemDetail: String = "Home/ScheduleItemDetail"
		internal static let SetPermissions: String = "Account/SetPermissions"
		internal static let ShareApp: String = "Payment/ShareApp"
		internal static let VerifyPhone: String = "Application/VerifyPhone"
	}
}
